language: java
sudo: false # faster builds

jdk:
  - openjdk8
  - oraclejdk8

cache:
  - directories:
    - $HOME/.m2

install: true

script:
  - travis_wait 30 mvn clean install -DskipTests=false -Dmaven.javadoc.skip=true -Drat.skip=false

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  -